exclude:
  - "lib/**"
  - "node_modules/**"
  - "dist/**"

linters:
  StringQuotes:
    enabled: true
    style: double_quotes
  Indentation:
    character: tab
    width: 1
  Comment:
    enabled: false
  LeadingZero:
    enabled: false
  SelectorDepth:
    enabled: false
  CapitalizationInSelector:
    exclude: "src/social-media-centre.scss"
  NameFormat:
    enabled: false
  UrlFormat:
    enabled: false
  ColorVariable:
    enabled: false
  IdSelector:
    enabled: false
  ImportantRule:
    enabled: false
  NestingDepth:
    enabled: false
