exclude:
  - "lib/**"
  - "node_modules/**"
  - "dist/**"

linters:
  StringQuotes:
    enabled: true
    style: double_quotes
  Indentation:
    width: 1
  LeadingZero:
    enabled: false
  SelectorDepth:
    enabled: false
  CapitalizationInSelector:
    exclude: "src/sass/social-media-centre.scss"
  NameFormat:
    enabled: false
