name: Continuos integration

on:
  pull_request:

jobs:
  integration-check:

    runs-on: ubuntu-latest

    environment: github-ci

    steps:
      - uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm i -g bower grunt-cli
          npm ci

      - name: Checkout wet-boew latest build
        if: ${{ env.ACT }}
        run: |
          git clone --depth 1 https://github.com/wet-boew/wet-boew-cdn.git --branch v4.0-dist ~wet-boew-cdn
          mkdir -p node_modules/wet-boew/dist/wet-boew
          mv ~wet-boew-cdn/* node_modules/wet-boew/dist/wet-boew

      - name: Build GCWeb
        if: ${{ !env.ACT }}
        run: grunt dist

      - name: Build GCWeb (without pre-test)
        if: ${{ env.ACT }}
        run: grunt dist-act
