name: Space Linting
on:
  push:
    branches-ignore:
      - "dependabot/**"
    paths:
      - "**"
      - "!**/*.{ico,jpg,png}"
      - "!**/*.{eot,svg,ttf,woff}"
      - ".github/workflows/lint-spaces.yml"

  pull_request:
    paths:
      - "**"
      - "!**/*.{ico,jpg,png}"
      - "!**/*.{eot,svg,ttf,woff}"
      - ".github/workflows/lint-spaces.yml"

jobs:
  lint-spaces:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm

      - name: Install Grunt
        run: npm i -g grunt-cli --force

      - name: Install npm dependencies
        run: npm ci

      - name: Lintspaces
        run: grunt lintspaces
